In [1]:
import pm4py
import sys
sys.path.append('../../../TaskExecutionTimeMining/')
from event_log_transformer import *
import pandas
pandas.set_option('display.max_columns', None)
pandas.set_option('display.max_rows', 200)

In [2]:
file_path = '../../../../data/helpdesk.csv'
event_log = pandas.read_csv(file_path)
event_log['id'] = event_log.index
event_log['Complete Timestamp'] = pandas.to_datetime(event_log['Complete Timestamp'])

In [3]:
event_log

,Case ID,Activity,Resource,Complete Timestamp,Variant,Variant index,Variant.1,seriousness,customer,product,responsible_section,seriousness_2,service_level,service_type,support_section,workgroup,id
0,Case 1,Assign seriousness,Value 1,2012-10-09 14:50:17,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,0
1,Case 1,Take in charge ticket,Value 1,2012-10-09 14:51:01,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,Value 1,1
2,Case 1,Take in charge ticket,Value 2,2012-10-12 15:02:56,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,2
3,Case 1,Resolve ticket,Value 1,2012-10-25 11:54:26,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,3
4,Case 1,Closed,Value 3,2012-11-09 12:54:39,Variant 12,12,Variant 12,Value 1,Value 1,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21343,Case 4579,Closed,Value 5,2010-09-02 10:11:00,Variant 1,1,Variant 1,Value 1,Value 71,Value 3,Value 1,Value 1,Value 3,Value 1,Value 1,Value 1,21343
21344,Case 4580,Take in charge ticket,Value 6,2012-01-03 09:33:43,Variant 18,18,Variant 18,Value 1,Value 92,Value 3,Value 1,Value 2,Value 2,Value 2,Value 1,Value 1,21344
21345,Case 4580,Wait,Value 6,2012-01-10 15:30:11,Variant 18,18,Variant 18,Value 1,Value 92,Value 3,Value 1,Value 2,Value 2,Value 2,Value 1,Value 1,21345
21346,Case 4580,Resolve ticket,Value 6,2012-01-10 17:07:40,Variant 18,18,Variant 18,Value 1,Value 92,Value 3,Value 1,Value 2,Value 2,Value 2,Value 1,Value 1,21346
21347,Case 4580,Closed,Value 5,2012-02-08 17:00:34,Variant 18,18,Variant 18,Value 1,Value 92,Value 3,Value 1,Value 2,Value 2,Value 2,Value 1,Value 1,21347

In [4]:
start_end_event_log = TransformEventLog.start_end_event_log_next(event_log,
                                 merge_activity_on = ['Case ID'],
                                 timestamp_name = 'Complete Timestamp',
                                 start_name_gen = '_start',
                                 complete_name_gen = '_complete',
                                 unique_column = 'id')

In [5]:
# Seconds in day
start_end_event_log = TransformEventLog.seconds_in_day(start_end_event_log, 'Complete Timestamp_start')
start_end_event_log = TransformEventLog.day_of_week(start_end_event_log, 'Complete Timestamp_start')

In [6]:
# Resource counts
start_end_event_log = TransformEventLog.value_count_per_case_without_lifecycle(start_end_event_log,
                                                             column_name = 'Activity_start',
                                                            case_name = 'Case ID',
                                                            timestamp_name = 'Complete Timestamp_start',
                                                            unique_id = 'id_start')
start_end_event_log = TransformEventLog.value_count_per_case_without_lifecycle(start_end_event_log,
                                                             column_name = 'Resource_start',
                                                            case_name = 'Case ID',
                                                            timestamp_name = 'Complete Timestamp_start',
                                                            unique_id = 'id_start')
start_end_event_log = start_end_event_log.sort_values(by='Complete Timestamp_start')

In [7]:
start_end_event_log

,Case ID,Activity_start,Resource_start,Complete Timestamp_start,Variant_start,Variant index_start,Variant.1_start,seriousness_start,customer_start,product_start,responsible_section_start,seriousness_2_start,service_level_start,service_type_start,support_section_start,workgroup_start,id_start,Activity_complete,Resource_complete,Complete Timestamp_complete,Variant_complete,Variant index_complete,Variant.1_complete,seriousness_complete,customer_complete,product_complete,responsible_section_complete,seriousness_2_complete,service_level_complete,service_type_complete,support_section_complete,workgroup_complete,id_complete,duration,duration_seconds,duration_ms,duration_hours,seconds_in_day,day_of_week,Assign seriousness,Closed,Create SW anomaly,DUPLICATE,INVALID,Insert ticket,RESOLVED,Require upgrade,Resolve SW anomaly,Resolve ticket,Schedule intervention,Take in charge ticket,VERIFIED,Wait,Value 1,Value 10,Value 11,Value 12,Value 13,Value 14,Value 15,Value 16,Value 17,Value 18,Value 19,Value 2,Value 20,Value 21,Value 22,Value 3,Value 4,Value 5,Value 6,Value 7,Value 8,Value 9
13241,Case 3608,Assign seriousness,Value 2,2010-01-13 08:40:25,Variant 33,33,Variant 33,Value 1,Value 63,Value 3,Value 5,Value 1,Value 2,Value 1,Value 4,Value 3,16857,Take in charge ticket,Value 2,2010-01-29 08:52:27,Variant 33,33,Variant 33,Value 1,Value 63,Value 3,Value 5,Value 1,Value 2,Value 1,Value 4,Value 3,16858,16 days 00:12:02,1383122.0,1.383122e+09,384.200556,31225,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
10108,Case 2748,Assign seriousness,Value 2,2010-01-13 12:26:04,Variant 1,1,Variant 1,Value 1,Value 52,Value 3,Value 7,Value 1,Value 2,Value 1,Value 3,Value 1,12863,Take in charge ticket,Value 2,2010-01-19 09:26:05,Variant 1,1,Variant 1,Value 1,Value 52,Value 3,Value 7,Value 1,Value 2,Value 1,Value 3,Value 1,12864,5 days 21:00:01,507601.0,5.076010e+08,141.000278,44764,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
15664,Case 4284,Assign seriousness,Value 2,2010-01-13 12:30:37,Variant 219,219,Variant 219,Value 1,Value 9,Value 3,Value 2,Value 2,Value 2,Value 2,Value 3,Value 1,19959,Assign seriousness,Value 2,2010-01-27 13:31:11,Variant 219,219,Variant 219,Value 1,Value 9,Value 3,Value 2,Value 2,Value 2,Value 2,Value 3,Value 1,19960,14 days 01:00:34,1213234.0,1.213234e+09,337.009444,45037,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
5631,Case 1534,Assign seriousness,Value 2,2010-01-13 13:09:31,Variant 33,33,Variant 33,Value 1,Value 176,Value 3,Value 4,Value 1,Value 2,Value 1,Value 3,Value 3,7168,Take in charge ticket,Value 2,2010-01-26 09:50:48,Variant 33,33,Variant 33,Value 1,Value 176,Value 3,Value 4,Value 1,Value 2,Value 1,Value 3,Value 3,7169,12 days 20:41:17,1111277.0,1.111277e+09,308.688056,47371,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1458,Case 406,Assign seriousness,Value 2,2010-01-13 17:25:25,Variant 4,4,Variant 4,Value 1,Value 143,Value 3,Value 4,Value 1,Value 2,Value 1,Value 3,Value 1,1864,Assign seriousness,Value 2,2010-01-13 17:25:38,Variant 4,4,Variant 4,Value 1,Value 143,Value 3,Value 4,Value 1,Value 2,Value 1,Value 3,Value 1,1865,0 days 00:00:13,13.0,1.300000e+04,0.003611,62725,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4206,Case 1156,Resolve ticket,Value 2,2013-12-19 10:02:24,Variant 2,2,Variant 2,Value 1,Value 22,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,5363,Closed,Value 3,2014-01-03 10:02:38,Variant 2,2,Variant 2,Value 1,Value 22,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,5364,15 days 00:00:14,1296014.0,1.296014e+09,360.003889,36144,3,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0
11069,Case 3013,Resolve ticket,Value 2,2013-12-19 10:03:46,Variant 28,28,Variant 28,Value 1,Value 20,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,14089,Closed,Value 3,2014-01-03 10:03:58,Variant 28,28,Variant 28,Value 1,Value 20,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,14090,15 days 00:00:12,1296012.0,1.296012e+09,360.003333,36226,3,1,0,0,0,0,0,0,0,0,1,0,2,0,1,0,0,0,0,0,0,0,0,0,1,0,3,1,0,0,0,0,0,0,0,0,0
14141,Case 3857,Resolve ticket,Value 2,2013-12-19 10:08:02,Variant 2,2,Variant 2,Value 1,Value 124,Value 6,Value 1,Value 1,Value 3,Value 1,Value 1,Value 1,18007,Closed,Value 3,2014-01-03 10:08:18,Variant 2,2,Variant 2,Value 1,Value 124,Value 6,Value 1,Value 1,Value 3,Value 1,Value 1,Value 1,18008,15 days 00:00:16,1296016.0,1.296016e+09,360.004444,36482,3,1,0,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0
9513,Case 2585,Resolve ticket,Value 1,2013-12-19 13:19:27,Variant 2,2,Variant 2,Value 1,Value 24,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,12104,Closed,Value 3,2014-01-03 13:19:48,Variant 2,2,Variant 2,Value 1,Value 24,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,12105,15 days 00:00:21,1296021.0,1.296021e+09,360.005833,47967,3,1,0,0,0,0,0,0,0,0,1,0,1,0,1,2,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
2150,Case 595,Resolve ticket,Value 1,2013-12-19 13:20:46,Variant 2,2,Variant 2,Value 1,Value 24,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,2745,Closed,Value 3,2014-01-03 13:20:58,Variant 2,2,Variant 2,Value 1,Value 24,Value 1,Value 1,Value 1,Value 2,Value 1,Value 1,Value 1,2746,15 days 00:00:12,1296012.0,1.296012e+09,360.003333,48046,3,1,0,0,0,0,0,0,0,0,1,0,1,0,1,2,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0

In [8]:
train, test = pm4py.ml.split_train_test(start_end_event_log, case_id_key='Case ID')

In [9]:
print(train.shape, test.shape)
print(train['Case ID'].unique().shape, test['Case ID'].unique().shape)

(13358, 75) (3397, 75)
(3661,) (919,)

In [10]:
train.to_csv('../../transformed_event_logs/Helpdesk_train.csv', index=False, date_format='%Y-%m-%d %H:%M:%S.%f')
train.to_pickle('../../transformed_event_logs/Helpdesk_train.pickle')

In [11]:
test.to_csv('../../transformed_event_logs/Helpdesk_test.csv', index=False, date_format='%Y-%m-%d %H:%M:%S.%f')
test.to_pickle('../../transformed_event_logs/Helpdesk_test.pickle')